### ISSUE TITLE
Dead ?

### ISSUE THREAD

**Issue by Jielde** [rendomnet/ultimate-launcher#1]
Hi,

Is the app not working?

**Comment by rendomnet** [comment]
What is not working?

**Comment by Jielde** [comment]
![image](https://user-images.githubusercontent.com/11017153/203399780-4ab4b140-1c23-4972-a5db-bcb6f9845c19.png)

Next button not work

**Comment by rendomnet** [comment]
@Jielde You need to connect patreon.

**Comment by Jielde** [comment]
Ok, thanks !

Doesn't Ultimate Launcher allow you to scan games locally like Playnite? I thought Ultimate Launcher could replace Playnite but I guess not.
